// TODO: Mock has to be updated according to the new data structure

export const recommendedProductsArray = [
  {
    'RECOMMENDATION_SMART_OFFERS|TODAY|NONE': [[Object], [Object], [Object]],
    'RECOMMENDATION_SOURCE_LAST_VISITED|THIS_WEEK|NONE': [[Object]],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'ASICS|MONTHLY|ROCK': [],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'RECOMMENDATION_SMART_OFFERS|TODAY|NONE': [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'RECOMMENDATION_SOURCE_LAST_VISITED|TODAY|NONE': [[Object]],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'RECOMMENDATION_SMART_OFFERS|THIS_WEEK|NONE': [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    'RECOMMENDATION_SOURCE_LAST_VISITED|THIS_WEEK|NONE': [[Object]],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'RECOMMENDATION_NEW_COMERS|MONTHLY|ROCK': [],
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
  },
  {
    'RECOMMENDATION_SOURCE_STATIC_ITEMS': [],
    'SPOR AKTİVİTELERİ > ANTRENMAN > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > ANTRENMAN > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > ANTRENMAN > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > ANTRENMAN|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > BASKETBOL > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > BASKETBOL > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > BASKETBOL > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > BASKETBOL|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > FUTBOL > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > FUTBOL > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > FUTBOL > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > FUTBOL|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > GÜNLÜK > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KAYAK & SNOWBOARD > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KAYAK & SNOWBOARD > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KAYAK & SNOWBOARD|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KOŞU & YÜRÜYÜŞ > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KOŞU & YÜRÜYÜŞ > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KOŞU & YÜRÜYÜŞ > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > KOŞU & YÜRÜYÜŞ|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > OUTDOOR > AKSESUAR|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > OUTDOOR > AYAKKABI|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > OUTDOOR > GIYIM|MONTHLY|ROCK': [],
    'SPOR AKTİVİTELERİ > OUTDOOR|MONTHLY|ROCK': [],
  },
  undefined,
];
