export const SEGMENTIFY_EVENTS = {
  PAGE_VIEW: 'PAGE_VIEW',
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  BASKET_OPERATIONS: 'BASKET_OPERATIONS',
  CHECKOUT: 'CHECKOUT',
  USER_OPERATIONS: 'USER_OPERATIONS',
  CUSTOM_EVENT: 'CUSTOM_EVENT',
  INTERACTION: 'INTERACTION',
  SEARCH: 'SEARCH',
};
